version: '3.8'

services:
  bot:
    image: amul-bot:latest
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - ./data:/app/data
    environment:
      # Override specific environment variables if needed
      - DATABASE_URL=${DATABASE_URL:-sqlite+aiosqlite:///app/data/amul_bot.db}
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "python", "-c", "import sqlite3; sqlite3.connect('/app/data/amul_bot.db')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
